# Allow all user agents
[[headers]]
  for = "/*"
  [headers.values]
    User-Agent = "*"
    X-Robots-Tag = "all"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "*"

# Optional: bypass route for staging if needed
[[redirects]]
  from = "/public/*"
  to = "/:splat"
  status = 200
  force = true
