// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  beSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Homebrewing',
      link: {
        type: 'generated-index',
        title: 'Homebrewing',
        description: 'Everything on this site about homebrewing — The Brewer\'s Manual science reference, the guided BrewClub programme, and recipes.',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Homebrewing',
        },
      ],
    },
    /*
    {
      type: 'category',
      label: 'A Year in Beer',
      link: {
        type: 'generated-index',
        title: 'A Year in Beer',
        description: 'Additional Resources for A Year in Beer',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'ayearinbeer/Beers',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference Library',
      link: {
        type: 'generated-index',
        title: 'Reference Library',
        description: 'Good books and other reference material',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Reference Library',
        },
      ],
    },
    */
  ],
};

module.exports = sidebars;
