/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  beSidebar: [
    'intro',
    //'glossary',
    /*{
      type: 'category',
      label: 'Homebrewing',
      link: {
        type: 'generated-index',
        title: 'Homebrewing Guides, Info & Recipes',
        description: 'What I\'ve Learnd and Know About Homebrewing...',
        //slug: '/category/docusaurus-guides',
        //keywords: ['guides'],
        //image: '/img/docusaurus.png',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Homebrewing',
        },
      ],
    },
    {
      type: 'category',
      label: 'A Year in Beer',
      link: {
        type: 'generated-index',
        title: 'A Year in Beer',
        description: 'Additional Resources for A Year in Beer',
        //slug: '/category/docusaurus-guides',
        //keywords: ['guides'],
        //image: '/img/docusaurus.png',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'ayearinbeer/Beers',
        },
      ],
    },

    {
      type: 'category',
      label: 'Style Guide',
      link: {
        type: 'generated-index',
        title: 'Style Guide',
        description: 'A Collection of Reference Material for Beer Styles',
        //slug: '/category/docusaurus-guides',
        //keywords: ['guides'],
        //image: '/img/docusaurus.png',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Style Guide',
        },
      ],
    },
    {
      type: 'category',
      label: 'Maps',
      link: {
        type: 'generated-index',
        title: 'Beer Maps',
        description: 'Where to Find Good Beer',
        //slug: '/category/docusaurus-guides',
        //keywords: ['guides'],
        //image: '/img/docusaurus.png',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Maps',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference Library',
      link: {
        type: 'generated-index',
        title: 'Reference Library',
        description: 'Good books and other reference material',
        //slug: '/category/docusaurus-guides',
        //keywords: ['guides'],
        //image: '/img/docusaurus.png',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Reference Library',
        },
      ],
    },*/
  ],

  // But you can create a sidebar manually
  /*
  mySidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
